Repository maistra/envoy, pull requests merged in 2020-11, with the labels that each got.

#55 Fixes MAISTRA-2015: backport of udp: properly handle truncated/droppe…
  include/envoy/network/io_handle.h
  source/common/network/io_socket_handle_impl.cc
  source/common/network/udp_listener_impl.h
  source/common/network/utility.cc
  test/common/network/udp_listener_impl_test.cc
  test/test_common/threadsafe_singleton_injector.h
Labels: okay to merge, size/L

#56 Fixes MAISTRA-2017: backport to Maistra-1.1: udp: properly handle tru…
  include/envoy/network/io_handle.h
  source/common/network/io_socket_handle_impl.cc
  source/common/network/udp_listener_impl.h
  source/common/network/utility.cc
  test/common/network/udp_listener_impl_test.cc
Labels: okay to merge, size/M

#53 MAISTRA-1977: Use a build cache
  maistra/run-ci.sh
Labels: okay to merge, size/XS

#57 MAISTRA-1898: Update to latest upstream 1.6
  VERSION
  docs/root/intro/version_history.rst
  include/envoy/http/header_map.h
  source/common/common/callback_impl.h
  source/common/http/BUILD
  source/common/http/header_map_impl.cc
  source/common/http/header_map_impl.h
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/runtime/BUILD
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  source/common/runtime/runtime_impl.cc
  source/extensions/common/wasm/context.cc
  source/extensions/filters/common/expr/BUILD
  source/extensions/filters/common/expr/context.cc
  source/extensions/filters/common/expr/context.h
  source/extensions/filters/common/expr/evaluator.cc
  source/extensions/filters/common/expr/evaluator.h
  source/extensions/filters/http/header_to_metadata/BUILD
  source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/extractor.cc
  source/extensions/filters/http/lua/BUILD
  source/extensions/filters/http/lua/wrappers.cc
  test/common/http/BUILD
  test/common/http/header_map_impl_test.cc
  test/common/http/header_utility_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/filters/common/expr/context_test.cc
  test/extensions/filters/common/expr/evaluator_fuzz_test.cc
  test/extensions/filters/http/header_to_metadata/header_to_metadata_filter_test.cc
  test/extensions/filters/http/jwt_authn/extractor_test.cc
  test/extensions/filters/http/lua/wrappers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/stats_integration_test.cc
  test/test_common/utility.h
Labels: okay to merge, size/XL
