Repository maistra/envoy, pull requests merged in 2020-09, with the labels that each got.

#39 MAISTRA-1166: Treat EAGAIN as SSL_ERROR_WANT_READ
  source/extensions/transport_sockets/tls/ssl_socket.cc
Labels: size/XS

#41 Add script to be used by CI
  maistra/run-ci.sh
Labels: size/M

#40 MAISTRA-1810: check timeout period to ensure the delay is relative to…
  source/common/network/connection_impl.cc
  source/common/network/connection_impl.h
  test/common/network/connection_impl_test.cc
Labels: size/M

#43 Fixes MAISTRA-1840 : tracing: Fix spankind = CLIENT bug when sharedSpanContext is
  source/extensions/tracers/zipkin/tracer.cc
  test/extensions/tracers/zipkin/tracer_test.cc
Labels: size/M

#45 Fixes MAISTRA-1840
  source/extensions/tracers/zipkin/tracer.cc
  test/extensions/tracers/zipkin/tracer_test.cc
Labels: okay to merge, size/M
