Repository maistra/envoy, pull requests merged in 2020-10, with the labels that each got.

#48 MAISTRA-1891: Handle EAGAIN response as SSL_ERROR_WANT_WRITE
  source/extensions/transport_sockets/tls/ssl_socket.cc
Labels: okay to merge, size/S

#47 MAISTRA-1921: Support dynamic crypto based on environment
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
Labels: okay to merge, size/M

#46 [WIP] MAISTRA-1166: Treat EAGAIN as SSL_ERROR_WANT_READ
  source/extensions/transport_sockets/tls/ssl_socket.cc
Labels: okay to merge, size/XS

#50 MAISTRA-1934: Support dynamic crypto based on environment
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
Labels: okay to merge, size/M

#51 MAISTRA-1935: Handle EAGAIN response as SSL_ERROR_WANT_WRITE
  source/extensions/transport_sockets/tls/ssl_socket.cc
Labels: okay to merge, size/S

#52 Maistra 1860
  source/common/network/connection_impl.cc
  source/common/network/connection_impl_base.cc
  source/common/network/connection_impl_base.h
  test/common/network/connection_impl_test.cc
Labels: okay to merge, size/M
