Repository maistra/envoy, pull requests merged in 2021-01, with the labels that each got.

#59 Replaced local_resources with local_ram_resources and local_cpu_resources
  bazel/repository_locations.bzl
  maistra/run-ci.sh
Labels: size/XS

#61 Use gcc 9
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/non--crash-security--bug.md
  .github/ISSUE_TEMPLATE/other.md
  .github/stale.yml
  .github/workflows/codeql-daily.yml
  .github/workflows/codeql-push.yml
  .github/workflows/get_build_targets.sh
  maistra/run-ci.sh
  test/integration/BUILD
Labels: don't squash, okay to merge, size/L

#64 MAISTRA-1475: Use host's toolchain for emscripten
  bazel/repository_locations.bzl
Labels: size/XS

#65 dummy commit
  WORKSPACE
Labels: size/XS

#66 MAISTRA-1475: Use host's toolchain for emscripten
  bazel/repository_locations.bzl
Labels: okay to merge, size/XS
