Repository maistra/envoy, pull requests merged in 2022-10, with the labels that each got.

#210 OSSM-1956: s390x fix for quiche
  bazel/external/quiche-s390x-support.patch
  bazel/repositories.bzl
Labels: size/S, okay to merge, ok-to-test

#211 OSSM-1801 Fixed pathlen constraint on test certificate and re enabled test
  test/config/integration/certs/client2cert.pem
  test/config/integration/certs/client2cert_hash.h
  test/config/integration/certs/intermediate_ca_2cert.pem
  test/config/integration/certs/intermediate_ca_2cert_info.h
  test/config/integration/certs/intermediate_ca_2key.pem
  test/config/integration/certs/intermediate_ca_cert_chain.pem
  test/config/integration/certs/intermediate_cacert.cfg
  test/config/integration/certs/intermediate_cacert.pem
  test/config/integration/certs/intermediate_cacert_info.h
  test/config/integration/certs/intermediate_cakey.pem
  test/extensions/transport_sockets/tls/cert_validator/default_validator_integration_test.cc
Labels: size/L, okay to merge

#209 Fix OSSM-1803: tls_inspector_integration_test FAILED
  test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
Labels: size/S, okay to merge

#212 OSSM 1802: fixed by taking modifications from upstream
  test/server/listener_manager_impl_test.cc
Labels: size/S, okay to merge
