Repository maistra/envoy, pull requests merged in 2022-03, with the labels that each got.

#138 [2.0] cherry-pick #103 - add luajit patches
  bazel/foreign_cc/luajit-s390x.patch
  bazel/foreign_cc/luajit.patch
  bazel/repositories.bzl
Labels: size/XXL, okay to merge

#139 MAISTRA-2648: WASM fix for s390x [maistra-2.2]
  bazel/external/proxy-wasm-cpp-host-s390x-support.patch
  bazel/repositories.bzl
Labels: size/L, okay to merge, ok-to-test

#134 MAISTRA-2648: WASM fix for s390x
  bazel/external/proxy_wasm_s390x.patch
  bazel/repositories.bzl
Labels: size/L, okay to merge, ok-to-test

#142 Ensure librdkafka configured correctly if compiler warnings are disabled
  bazel/foreign_cc/BUILD
Labels: size/XS, okay to merge

#147 Revert "MAISTRA-2648: WASM fix for s390x"
  bazel/external/proxy_wasm_s390x.patch
  bazel/repositories.bzl
Labels: size/L, okay to merge

#148 Point issues to Red Hat Jira
  .github/ISSUE_TEMPLATE/config.yml
  .github/actions/pr_notifier/requirements.txt
  .github/workflows/check-deps.yml
  README.md
Labels: size/L, okay to merge

#149 Revert "MAISTRA-2648: WASM fix for s390x (#139)"
  bazel/external/proxy-wasm-cpp-host-s390x-support.patch
  bazel/repositories.bzl
Labels: size/L, okay to merge

#140 [2.2] A few tweaks
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/io_handle_bio.cc
  source/extensions/transport_sockets/tls/openssl_impl.cc
  source/extensions/transport_sockets/tls/openssl_impl.h
  source/extensions/transport_sockets/tls/ssl_handshaker.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
Labels: size/M, okay to merge
