Repository maistra/envoy, pull requests merged in 2022-06, with the labels that each got.

#169 OSSM-1344: Fixing issues for ppc64le
  bazel/BUILD
  bazel/external/wee8-s390x-ppc64.patch
  bazel/foreign_cc/luajit2.patch
  bazel/repositories.bzl
Labels: size/M, okay to merge, ok-to-test

#170 [2.1] Fix leaking BIO_METHOD objects
  source/extensions/transport_sockets/tls/io_handle_bio.cc
Labels: size/S, okay to merge

#172 Fix the build/test on ppc
  bazel/BUILD
Labels: size/XS, okay to merge

#178 [maistra-2.0] OSSM-1297: Use a remote build cache, if it exists (#160)
  maistra/run-ci.sh
Labels: size/S, okay to merge
