Repository maistra/envoy, pull requests merged in 2023-10, with the labels that each got.

#290 Sync 1.24
  .azure-pipelines/pipelines.yml
  .github/actions/pr_notifier/requirements.txt
  bazel/repository_locations.bzl
  ci/Dockerfile-envoy
  ci/do_ci.sh
  contrib/kafka/filters/network/source/protocol/generator.py
  docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
  docs/root/configuration/listeners/network_filters/kafka_mesh_filter.rst
  examples/brotli/service.py
  examples/ext_authz/auth/grpc-service/go.mod
  examples/ext_authz/auth/grpc-service/go.sum
  examples/grpc-bridge/client/requirements.in
  examples/grpc-bridge/server/go.mod
  examples/grpc-bridge/server/go.sum
  examples/gzip/service.py
  examples/shared/flask/requirements.in
  examples/shared/flask/requirements.txt
  examples/shared/tracing/requirements.in
  examples/shared/tracing/requirements.txt
  examples/zstd/Dockerfile-service
  tools/base/requirements.in
  tools/base/requirements.txt
  tools/dependency/requirements.txt
Labels: size/XXL, okay to merge, tide/merge-method-merge

#295 [Maistra 2.3] CVE - Denial of service when using HTTP/2 protocol
  changelogs/current.yaml
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_impl.cc
  source/common/http/conn_manager_impl.h
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/http/http1/codec_impl.cc
  source/common/runtime/runtime_features.cc
  test/common/http/conn_manager_impl_test_2.cc
  test/common/http/conn_manager_impl_test_base.cc
  test/common/http/conn_manager_impl_test_base.h
  test/common/http/http2/http2_frame.cc
  test/common/http/http2/http2_frame.h
  test/common/io/io_uring_impl_test.cc
  test/integration/multiplexed_integration_test.cc
  test/integration/tcp_tunneling_integration_test.cc
Labels: size/XXL, okay to merge

#298 [Maistra-2.3] Http2 CVE tests added
  test/common/http/conn_manager_impl_test_2.cc
Labels: size/L, okay to merge
