Repository maistra/envoy, pull requests merged in 2023-05, with the labels that each got.

#269 [MAISTRA-2.3] OSSM-1956: Restore s390x fix for quiche (#210)
  bazel/repositories.bzl
Labels: size/XS, okay to merge, auto-merge

#270 Maistra 2.4 to 1.24.7
  .azure-pipelines/bazel.yml
  .azure-pipelines/pipelines.yml
  .bazelrc
  RELEASES.md
  VERSION.txt
  bazel/dependency_imports.bzl
  bazel/foreign_cc/curl.patch
  bazel/proxy_wasm_cpp_host.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  changelogs/1.22.10.yaml
  changelogs/1.22.11.yaml
  changelogs/1.22.9.yaml
  changelogs/1.23.6.yaml
  changelogs/1.23.7.yaml
  changelogs/1.23.8.yaml
  changelogs/1.23.9.yaml
  changelogs/1.24.4.yaml
  changelogs/1.24.5.yaml
  changelogs/1.24.6.yaml
  changelogs/1.24.7.yaml
  changelogs/current.yaml
  ci/Dockerfile-envoy
  ci/build_setup.sh
  ci/do_ci.sh
  ci/filter_example_mirror.sh
  ci/run_clang_tidy.sh
  ci/run_envoy_docker.sh
  ci/setup_cache.sh
  docs/build.sh
  docs/inventories/v1.22/objects.inv
  docs/inventories/v1.23/objects.inv
  docs/inventories/v1.24/objects.inv
  docs/versions.yaml
  examples/websocket/Dockerfile-websocat
  examples/websocket/Dockerfile-websocat-client
  source/common/http/conn_manager_utility.cc
  source/common/http/header_utility.cc
  source/common/version/version.cc
  test/common/http/conn_manager_utility_test.cc
  test/common/http/header_utility_test.cc
  test/integration/filters/invalid_header_filter.cc
  test/integration/protocol_integration_test.cc
  tools/proto_format/proto_format.sh
Labels: okay to merge, size/XL, tide/merge-method-merge

#263 [Maistra 2.4] OSSM-2208: With multiple cert chains, SSL handshake may fail
  source/extensions/transport_sockets/tls/context_impl.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: size/M, okay to merge, tide/merge-method-merge

#272 Client Cipher update for OSSM-1667
  source/extensions/transport_sockets/tls/context_config_impl.cc
Labels: size/S, okay to merge

#231 Use local python instead of bazel toolchain python
  bazel/python_dependencies.bzl
Labels: size/XS, okay to merge

#274 Revert "Removed rules_license dependency. (#273)"
  bazel/repository_locations.bzl
Labels: size/S, okay to merge

#275 Bump to the version used by Istio 1.16.5
  bazel/foreign_cc/ipp-crypto-skip-dynamic-lib.patch
  bazel/repositories.bzl
  changelogs/current.yaml
  contrib/qat/BUILD
Labels: size/M, okay to merge, tide/merge-method-merge
