Repository maistra/envoy, pull requests merged in 2023-07, with the labels that each got.

#277 Maistra 2.4 update from upstream 1.24
  .azure-pipelines/cleanup.sh
  .azure-pipelines/pipelines.yml
  VERSION.txt
  bazel/envoy_build_system.bzl
  bazel/foreign_cc/librdkafka.patch
  bazel/foreign_cc/vpp_vcl.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  changelogs/1.23.10.yaml
  changelogs/1.24.8.yaml
  changelogs/current.yaml
  contrib/kafka/filters/network/source/mesh/BUILD
  contrib/kafka/filters/network/source/mesh/inbound_record.h
  contrib/kafka/filters/network/source/mesh/librdkafka_utils.h
  contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.cc
  contrib/kafka/filters/network/source/mesh/librdkafka_utils_impl.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.cc
  contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.cc
  contrib/kafka/filters/network/source/mesh/upstream_kafka_consumer_impl.h
  contrib/kafka/filters/network/test/mesh/BUILD
  contrib/kafka/filters/network/test/mesh/kafka_mocks.h
  contrib/kafka/filters/network/test/mesh/upstream_kafka_client_impl_unit_test.cc
  contrib/kafka/filters/network/test/mesh/upstream_kafka_consumer_impl_unit_test.cc
  contrib/vcl/source/BUILD
  contrib/vcl/source/vcl_build_launcher.py
  contrib/vcl/source/vpp_vcl_build.sh
  docs/inventories/v1.23/objects.inv
  docs/inventories/v1.24/objects.inv
  docs/versions.yaml
  source/common/upstream/original_dst_cluster.h
  test/common/upstream/original_dst_cluster_test.cc
  test/extensions/filters/http/ext_proc/test_processor.cc
  tools/dependency/cve.yaml
Labels: size/XXL, okay to merge, tide/merge-method-merge

#278 [maistra 2.2] OSSM-3554: various CVEs fixed
  bazel/external/wee8-vector.patch
  bazel/repositories.bzl
  docs/root/version_history/current.rst
  source/common/http/BUILD
  source/common/http/conn_manager_impl.cc
  source/common/http/conn_manager_utility.cc
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http2/codec_impl.cc
  source/common/protobuf/utility.cc
  source/common/protobuf/utility.h
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_server_stream.cc
  source/common/quic/envoy_quic_server_stream.h
  source/common/quic/envoy_quic_stream.h
  source/common/runtime/runtime_features.cc
  source/common/singleton/threadsafe_singleton.h
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  source/extensions/access_loggers/grpc/http_grpc_access_log_impl.cc
  source/extensions/filters/common/ext_authz/check_request_utils.cc
  source/extensions/filters/http/ext_proc/mutation_utils.cc
  source/extensions/filters/http/lua/lua_filter.cc
  source/extensions/filters/http/lua/lua_filter.h
  source/extensions/filters/http/oauth2/filter.cc
  source/extensions/filters/http/tap/tap_config_impl.cc
  source/server/server.cc
  test/common/http/conn_manager_utility_test.cc
  test/common/http/header_utility_test.cc
  test/common/http/http1/codec_impl_test.cc
  test/common/http/http2/codec_impl_test.cc
  test/common/protobuf/utility_test.cc
  test/common/quic/envoy_quic_client_stream_test.cc
  test/common/quic/envoy_quic_server_stream_test.cc
  test/extensions/access_loggers/grpc/http_grpc_access_log_impl_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/lua/lua_integration_test.cc
  test/extensions/filters/http/oauth2/oauth_integration_test.cc
  test/extensions/filters/http/tap/tap_config_impl_test.cc
  test/integration/filters/invalid_header_filter.cc
  test/integration/http_protocol_integration.h
  test/integration/protocol_integration_test.cc
  test/integration/quic_http_integration_test.cc
  test/server/BUILD
  test/server/config_validation/config_fuzz_test.cc
  test/server/server_fuzz_test.cc
  test/test_common/test_runtime.h
  tools/spelling/spelling_dictionary.txt
Labels: size/XXL, okay to merge, tide/merge-method-merge

#281 [Maistra 2.4] Re-enable signal_tests and async_file_handle_thread_pool_test
  maistra/run-ci.sh
Labels: size/XS, okay to merge

#271 Added support for setting Bazel's --experimental_remote_downloader option
  maistra/common.sh
Labels: size/XS, okay to merge

#282 Maistra 2.3 update s
  bazel/foreign_cc/nghttp2.patch
  docs/root/version_history/current.rst
  source/common/http/conn_manager_utility.cc
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/http/utility.cc
  source/common/http/utility.h
  source/common/router/config_impl.cc
  source/common/router/router.cc
  source/common/runtime/runtime_features.cc
  source/extensions/access_loggers/open_telemetry/config.cc
  source/extensions/filters/common/mutation_rules/mutation_rules.cc
  source/extensions/filters/http/cache/cacheability_utils.cc
  source/extensions/filters/http/cache/http_cache.cc
  source/extensions/filters/http/cors/cors_filter.cc
  source/extensions/filters/http/cors/cors_filter.h
  source/extensions/filters/http/oauth2/filter.cc
  test/common/http/utility_test.cc
  test/extensions/access_loggers/open_telemetry/access_log_integration_test.cc
  test/extensions/filters/http/cors/cors_filter_test.cc
  test/extensions/filters/http/oauth2/filter_test.cc
  test/integration/filters/test_socket_interface.cc
  test/integration/filters/test_socket_interface.h
  test/integration/http2_flood_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/socket_interface_swap.cc
  test/integration/socket_interface_swap.h
Labels: okay to merge, size/XL, tide/merge-method-merge
