Repository maistra/envoy, pull requests merged in 2024-09, with the labels that each got.

#322 reenable TLSv1.3 for FIPS mode
  source/extensions/transport_sockets/tls/context_config_impl.cc
Labels: size/XS, okay to merge, needs-ok-to-test

#326 stateful_session: encode expiry time and reject expired cookies (#26761)
  api/envoy/type/http/v3/cookie.proto
  changelogs/current.yaml
  source/common/runtime/runtime_features.cc
  source/extensions/http/stateful_session/cookie/BUILD
  source/extensions/http/stateful_session/cookie/config.cc
  source/extensions/http/stateful_session/cookie/cookie.cc
  source/extensions/http/stateful_session/cookie/cookie.h
  source/extensions/http/stateful_session/cookie/cookie.proto
  test/extensions/filters/http/stateful_session/stateful_session_integration_test.cc
  test/extensions/http/stateful_session/cookie/BUILD
  test/extensions/http/stateful_session/cookie/cookie_test.cc
  tools/code_format/config.yaml
Labels: size/XXL, okay to merge

#328 2.4 updates 1
  changelogs/current.yaml
  source/extensions/compression/brotli/decompressor/brotli_decompressor_impl.cc
  source/extensions/compression/brotli/decompressor/brotli_decompressor_impl.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/context_impl.h
  source/extensions/transport_sockets/tls/ssl_socket.cc
  source/extensions/transport_sockets/tls/ssl_socket.h
  test/extensions/compression/brotli/decompressor/brotli_decompressor_impl_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
Labels: size/L, okay to merge
