Repository maistra/envoy, pull requests merged in 2024-02, with the labels that each got.

#306 [maistra-2.4] OSSM-5850: ext_authz: ensure both raw body/body will be used for http authorization request (#27228)
  changelogs/current.yaml
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
  test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
Labels: size/M, okay to merge, tide/merge-method-merge

#307 Fix for OSSM-5962
  maistra/run-ci.sh
  source/extensions/transport_sockets/tls/openssl_impl.cc
Labels: size/M, okay to merge

#308 Fixed ppc64le proxy build issue for go-protoc-bin
  bazel/rules_go.patch
Labels: size/S, okay to merge, ok-to-test

#310 [MAISTRA-2.5] CI TIMEOUT workaround: use bazel "flaky_test_attempt" option
  maistra/run-ci.sh
Labels: size/M, okay to merge
